### ISSUE TITLE
How to install this on Windows?

### ISSUE THREAD

**Issue by AqlaSolutions** [nkiraly/DBSteward#109]
I downloaded composer, it found that I have php.exe - ok, use it - no, there is no SSL. So I should get php, than may be you need apache and that's just composer, even not DBSteward itself!

I DON'T WANT TO PLAY QUESTS! 

Is there a normal exe installer so I can just download it and click next-next-finish?

Or at least step by step instruction for windows?

**Comment by AqlaSolutions** [comment]
1. I downloaded php, had to set extension dir to ext, ok
2. openssl ext - uncommeted, ok
3. oh, it needs also pgsql ext.. IT'S NOT PRESENT IN THE INSTRUCTION!
4. now I have "Could not locate xmllint executable" <-- IT'S NOT PRESENT IN THE INSTRUCTION TOO!

**Comment by AqlaSolutions** [comment]
Excuse me for being too impatient, I've installed and it was just sooo not obvious! I mean I had too google several times before I realized how to setup everything.

**Comment by nkiraly** [comment]
PHP has docs for the various ways you can get PHP running on windows
http://php.net/manual/en/install.windows.commandline.php

You should consider running Babun http://babun.github.io/ and installing PHP and any extensions you need that way with *pact*.

After getting the CLI SAPI up and running, you can install composer with it's windows installer or use the composer install commands listed on https://getcomposer.org/download/

With composer running, following the install docs https://github.com/nkiraly/DBSteward/blob/master/doc/INSTALLING.md will allow composer to confirm you have all DBSteward run time PHP extension dependencies available.
