### ISSUE TITLE
DBSteward doesn't produce migration scripts for renamed column

### ISSUE THREAD

**Issue by AqlaSolutions** [nkiraly/DBSteward#110]
I renamed one column, so I have 2 xml files with:

1. &lt;column name=&quot;admin_level&quot; type=&quot;integer&quot; null=&quot;false&quot; default=&quot;0&quot;/&gt;

2. &lt;column name=&quot;admin_level1&quot; type=&quot;integer&quot; null=&quot;false&quot; default=&quot;0&quot;/&gt;

I expected it to at least generate "drop column" and "add column" but the output files doesn't contain anything....

[output.zip](https://github.com/nkiraly/DBSteward/files/81107/output.zip)

C:\Users\Vlad\AppData\Roaming\Composer\vendor\bin>dbsteward --oldxml=structure1.xml --newxml=structure2.xml
NOTICE   DBSteward Version 1.4.2
NOTICE   XML file(s) are targeted for sqlformat=pgsql8
NOTICE   Using sqlformat=pgsql8
NOTICE   Loading XML C:\Users\Vlad\AppData\Roaming\Composer\vendor\bin\structure1.xml..
NOTICE   Compositing XML File structure1.xml
NOTICE   Loading XML C:\Users\Vlad\AppData\Roaming\Composer\vendor\bin\structure2.xml..
NOTICE   Compositing XML File structure2.xml
NOTICE   Saving oldxml composite as ./structure1_composite.xml
NOTICE   Saving newxml composite as ./structure2_composite.xml
WARNING  table public.users has been processed as a dependency more than 3 times as many total tables; skipping further reordering
WARNING  table public.users has been processed as a dependency more than 3 times as many total tables; skipping further reordering
WARNING  table public.users has been processed as a dependency more than 3 times as many total tables; skipping further reordering
WARNING  table public.users has been processed as a dependency more than 3 times as many total tables; skipping further reordering
WARNING  table public.users has been processed as a dependency more than 3 times as many total tables; skipping further reordering
WARNING  table public.users has been processed as a dependency more than 3 times as many total tables; skipping further reordering
WARNING  table public.users has been processed as a dependency more than 3 times as many total tables; skipping further reordering
WARNING  table public.users has been processed as a dependency more than 3 times as many total tables; skipping further reordering
WARNING  table public.users has been processed as a dependency more than 3 times as many total tables; skipping further reordering
WARNING  table public.users has been processed as a dependency more than 3 times as many total tables; skipping further reordering
WARNING  table public.users has been processed as a dependency more than 3 times as many total tables; skipping further reordering
WARNING  table public.users has been processed as a dependency more than 3 times as many total tables; skipping further reordering
WARNING  table public.users has been processed as a dependency more than 3 times as many total tables; skipping further reordering
WARNING  table public.users has been processed as a dependency more than 3 times as many total tables; skipping further reordering
WARNING  table public.users has been processed as a dependency more than 3 times as many total tables; skipping further reordering
WARNING  table public.users has been processed as a dependency more than 3 times as many total tables; skipping further reordering
WARNING  table public.users has been processed as a dependency more than 3 times as many total tables; skipping further reordering
WARNING  table public.users has been processed as a dependency more than 3 times as many total tables; skipping further reordering
WARNING  table public.users has been processed as a dependency more than 3 times as many total tables; skipping further reordering
WARNING  table public.users has been processed as a dependency more than 3 times as many total tables; skipping further reordering
NOTICE   [File Segment] Opening output file segement ./structure2_upgrade_stage1_schema1.sql
NOTICE   [File Segment] Opening output file segement ./structure2_upgrade_stage2_data1.sql
ERROR    Reserved identifier: 'time' - turn on quoting of reserved identifiers with --quotereservednames
NOTICE   [File Segment] Opening output file segement ./structure2_upgrade_stage3_schema1.sql
NOTICE   [File Segment] Opening output file segement ./structure2_upgrade_stage4_data1.sql

**Comment by nkiraly** [comment]
Two things you need to correct to get desired output:

1) Use --quotereservednames in your command line call as it appears you have a database object called time. As a result of that finding, the error line
```bash
ERROR Reserved identifier: 'time' - turn on quoting of reserved identifiers with --quotereservednames
```
is where differencing and SQL output was halted.

2) Column renaming behaviors

2a) If you expect the column to be dropped and a new one added, your XML is correct and after adding the --quotereservednames command line option, you will see admin_level1 column being added in stage 1 and admin_level dropped in stage 3.

2b) If you want generated SQL upgrade files to rename the column, you must hint that the column existed as the previous name with
```XML
<column name="admin_level1" oldColumnName="admin_level" type="integer" null="false" default="0"/>
```

As a final change control step, the version after the version where you renamed a column, you should remove the oldColumnName attribute.

For more details on renaming columns, check out XMLGUIDE's sections 5 and 6 on column renaming and data transforms: https://github.com/nkiraly/DBSteward/blob/master/doc/XMLGUIDE.md#5-notating-table-or-column-renaming

**Comment by AqlaSolutions** [comment]
Thank you, that works!
