### ISSUE TITLE
mysql driver does not handle composite foreign key "magic indexes"

### ISSUE THREAD

**Issue by austinhyde** [nkiraly/DBSteward#88]
As of b7bb1df, the mysql driver creates "magic indexes" for single-column foreign keys, to match how MySQL handles foreign keys/indexes.

Once #87 is done, expand this behavior to composite foreign keys by looking for foreignKey elements.

**Comment by nkiraly** [comment]
moving this to 1.4.1 milestone to get existing changes out there for mysql users
