### ISSUE TITLE
Generate EXECUTE SCRIPT slonik

### ISSUE THREAD

**Issue by austinhyde** [nkiraly/DBSteward#89]
DBSteward has historically not included the EXECUTE SCRIPT commands to run stage 1 and stage 3 schema changes after all slonik stage 1 and 3 commands have been executed.

Update slonik output to include EXECUTE SCRIPT statements to run these files. There is no reason not to be doing this at this point.

**Comment by nkiraly** [comment]
Implemented in https://github.com/nkiraly/DBSteward/pull/90

I tested this by developing https://github.com/nkiraly/dbsteward-maven-plugin/issues/1

Working as of https://github.com/nkiraly/dbsteward-maven-plugin/commit/1900aaa1613715d0a0755931da8b297c6342ad1b  1.4.0-SNAPSHOT
